version: '3.8'

services:
   node-app:
      build: .
      container_name: full_app
      ports:
         - 3000:3000
      restart: always
      depends_on:
         - mongo_db
      networks:
         - node_network

   mongo_db:
      image: mongo:latest
      restart: always
      container_name: full_mongodb
      ports:
         - 27017:27017
      volumes:
         - dbdata:/data/db
      networks:
         - node_network

volumes:
   dbdata:

networks:
   node_network:
      driver: bridge
